import type {
  Acknowledgement,
  AssistantCatalog,
  ExtractionResult,
  UnroutableOperation,
} from "./assistant-catalog-types.ts";
import { acknowledgements } from "./assistant-gate.ts";
import { operationInventory } from "./assistant-operation-inventory.ts";

export function renderCatalog(catalog: AssistantCatalog): string {
  return `${JSON.stringify(catalog, null, 2)}\n`;
}

export function renderCapabilities(catalog: AssistantCatalog): string {
  const visible = catalog.operations.filter((operation) => !operation.hidden);
  const groups = [...new Set(visible.map((operation) => operation.group))];
  const lines = [
    "<!-- Generated by pnpm gen:assistant-catalog from packages/web/src/engine-adapter. Do not edit. -->",
    "# TilinX assistant capabilities",
    "",
    "Everything the assistant can do in TilinX, derived from the live engine adapter.",
    "",
    "Calling an operation returns the host's raw response. Where the adapter function also post-processes that response (unwrapping `items`, 404 fallbacks), the catalog records it as `rawResponse` and the post-processing is not applied.",
  ];
  for (const group of groups) {
    lines.push("", `## ${group}`, "");
    for (const operation of visible.filter((item) => item.group === group)) {
      lines.push(
        `- \`${operation.name}\`: ${operation.description}${operation.confirm ? " **Confirmation required.**" : ""}${operation.route ? "" : " (not callable yet)"}`,
      );
    }
  }
  return `${lines.join("\n")}\n`;
}

/**
 * The CAPABILITY INDEX the coordinator carries in its always-on context: one
 * line per group, naming every operation in it.
 *
 * It exists because a model that has to SEARCH before it knows a thing exists
 * will sometimes answer from memory instead, and answer wrong — TilinX told a
 * user missions cannot be deleted while `deleteActivity` sat in the catalog,
 * visible. Names only, so the whole surface fits in a paragraph and the model
 * always knows what to reach for; the contract of any one of them is still read
 * with `tilinx_describe`.
 *
 * Emitted as a TypeScript module in DOMAIN rather than a document: the runtime
 * builds the coordinator's prompt from it, so it must travel inside the bundle
 * (the container image and the Bun-compiled desktop sidecar alike) with nothing
 * to locate on disk. Regenerated with the catalog and drift-gated by
 * `pnpm check:assistant-catalog`, so a new operation reaches the assistant's
 * context the moment it is annotated.
 */
export function renderCapabilityIndex(catalog: AssistantCatalog): string {
  const visible = catalog.operations.filter((operation) => !operation.hidden);
  const groups = [...new Set(visible.map((operation) => operation.group))];
  const index = [
    "# What TilinX can do",
    "",
    "Every action you can perform for the user, by area. This is the whole list: if something is not here, search tilinx_capabilities before you tell the user it cannot be done.",
    "",
    ...groups.map(
      (group) =>
        `- ${group}: ${visible
          .filter((operation) => operation.group === group)
          .map((operation) => operation.name)
          .join(", ")}`,
    ),
    "",
    "Read one with tilinx_describe before you use it, then perform it with tilinx_call.",
  ].join("\n");
  return `${[
    "// Generated by pnpm gen:assistant-catalog from packages/web/src/engine-adapter. Do not edit.",
    "",
    "/**",
    " * The coordinator's map of everything it can do in TilinX: one line per",
    " * catalog group, naming the operations in it. Injected into the personal",
    " * assistant's always-on context beside its operating rules",
    " * (packages/runtime/src/session/assistant-rules-context.ts), so the model",
    " * knows the surface exists without having to search for it first.",
    " */",
    `export const ASSISTANT_CAPABILITY_INDEX = ${JSON.stringify(index)};`,
  ].join("\n")}\n`;
}

function section(title: string, values: string[]): string[] {
  return [
    `## ${title} (${values.length})`,
    "",
    ...(values.length > 0
      ? values.map((value) => `- \`${value}\``)
      : ["None."]),
  ];
}

function unroutableSection(values: UnroutableOperation[]): string[] {
  return [
    `## Unroutable operations (${values.length})`,
    "",
    "No HTTP route could be derived conservatively from the function body, so the operation is not callable.",
    "",
    ...(values.length > 0
      ? values.map(({ name, reason }) => `- \`${name}\`: ${reason}`)
      : ["None."]),
  ];
}

function acknowledgedSection(
  title: string,
  lead: string,
  values: Acknowledgement[],
): string[] {
  return [
    `## ${title} (${values.length})`,
    "",
    lead,
    "",
    ...(values.length > 0
      ? values.map(
          ({ name, kind, reason }) => `- \`${name}\` - ${kind}: ${reason}`,
        )
      : ["None."]),
  ];
}

export function renderCoverage({
  catalog,
  coverage,
  annotations,
}: ExtractionResult): string {
  const stated = acknowledgements(annotations);
  const debt = stated.filter((item) => item.debt);
  const exceptions = stated.filter((item) => !item.debt);
  const documented = catalog.operations.length - coverage.undocumented.length;
  const rawResponse = catalog.operations.filter(
    (operation) => operation.route?.rawResponse,
  ).length;
  return `${[
    "<!-- Generated by pnpm gen:assistant-catalog from packages/web/src/engine-adapter. Do not edit. -->",
    "# TilinX assistant catalog coverage",
    "",
    `- Operations: ${catalog.operations.length}`,
    `- Documented: ${documented}`,
    `- Undocumented: ${coverage.undocumented.length}`,
    `- Ungrouped: ${coverage.ungrouped.length}`,
    `- Unschematized: ${coverage.unschematized.length}`,
    `- Hidden: ${coverage.hidden.length}`,
    `- Routable: ${catalog.operations.length - coverage.unroutable.length}`,
    `- Unroutable: ${coverage.unroutable.length}`,
    `- Raw-response routes: ${rawResponse}`,
    `- Acknowledged exceptions: ${exceptions.length}`,
    `- Acknowledged debt: ${debt.length}`,
    "",
    "A raw-response route reaches the host through an adapter function that post-processes the reply (unwrapping `items`, 404 fallbacks, `.then` transforms). The route itself carries the host's response unchanged.",
    "",
    ...acknowledgedSection(
      "Acknowledged exceptions",
      "Every operation the assistant cannot drive states why in its `@assistant` tag, and `pnpm check:assistant-coverage` fails the build on any that does not. These are the human-owned exceptions.",
      exceptions,
    ),
    "",
    ...acknowledgedSection(
      "Acknowledged debt",
      "Exceptions whose author says the operation SHOULD be automatable and is waiting on a refactor.",
      debt,
    ),
    "",
    ...section("Undocumented operations", coverage.undocumented),
    "",
    ...section("Ungrouped operations", coverage.ungrouped),
    "",
    ...section("Operations outside the group taxonomy", coverage.misgrouped),
    "",
    ...section("Unschematized fields", coverage.unschematized),
    "",
    ...section("Hidden operations", coverage.hidden),
    "",
    ...unroutableSection(coverage.unroutable),
    "",
    "Every operation's method, approval policy and parameter resolution: [assistant-operations.md](assistant-operations.md).",
  ].join("\n")}\n`;
}

/**
 * The per-operation ledger: what each operation does to the user's data, and
 * where every value it takes comes from. The coverage doc above judges whether
 * an operation is REACHABLE; this one is the policy an approver reads.
 */
export function renderOperations(catalog: AssistantCatalog): string {
  return `${[
    "<!-- Generated by pnpm gen:assistant-catalog from packages/web/src/engine-adapter. Do not edit. -->",
    "# TilinX assistant operations",
    "",
    "One row per catalog operation. [Coverage exceptions, schema gaps and route diagnostics](assistant-coverage.md).",
    "",
    ...operationInventory(catalog),
  ].join("\n")}\n`;
}
