import { readFileSync } from "node:fs";
import { ASSISTANT_CATALOG_VERSION } from "@tilinx/domain/assistant-catalog-types";
import ts from "typescript";
import {
  ASSISTANT_GROUPS,
  type AssistantOperation,
  type ExtractionResult,
  type OperationAnnotation,
  type UnroutableOperation,
} from "./assistant-catalog-types.ts";
import { readFileSurface } from "./assistant-declarations.ts";
import {
  humanizeMethodName,
  leadingJsDoc,
  parseAssistantDocs,
} from "./assistant-jsdoc.ts";
import {
  callerParameters,
  declarationLocation,
  parametersOf,
  returnsOf,
} from "./assistant-operation-parts.ts";
import { extractRoute } from "./assistant-route.ts";
import { isFallback, schemaForType } from "./assistant-schema.ts";
import { hashSources, sharedHelpers } from "./assistant-sources.ts";

const CATALOG_COMMENT =
  "Generated by pnpm gen:assistant-catalog from the live engine adapter (packages/web/src/engine-adapter). Do not edit. Every `path` is the FULL host path - nothing is prepended to it. A route carries its JSON body EITHER as `body` (one parameter sent whole) OR as `bodyFields` (body key -> parameter); a caller that reads only `body` sends an empty body for every `bodyFields` route. Each path parameter says how its value is escaped: `segment` is one URL segment, `path` keeps the `/` separators of a relative path. Every route returns the host response verbatim; `rawResponse: true` flags the ones whose adapter function additionally post-processes it (unwrapping `items`, 404 fallbacks, `.then` transforms), which a caller driving the route directly does not get. A parameter may also carry `description` (the author's `@param` line), `source` (the operation that LISTS the values it accepts), `resolver` (TilinX checks the value against that live list before it acts: pass the id, or the exact name the user said, and anything else comes back refused with the values that exist) and `unresolved` (why no live list backs this one). An identifier is never to be guessed: use the closed set in its `schema`, pass a name TilinX resolves, or call its `source` first.";

export interface ExtractOptions {
  /** Files whose published functions become operations, in precedence order. */
  operationSources: string[];
  /** Read only for the path helpers its templates share. */
  transportSource: string;
}

interface Collected {
  operations: AssistantOperation[];
  annotations: OperationAnnotation[];
  undocumented: string[];
  ungrouped: string[];
  misgrouped: string[];
  unschematized: string[];
  unroutable: UnroutableOperation[];
}

export function extractCatalog(options: ExtractOptions): ExtractionResult {
  const files = [...options.operationSources, options.transportSource];
  const program = ts.createProgram(files, {
    target: ts.ScriptTarget.ES2022,
    module: ts.ModuleKind.ESNext,
    moduleResolution: ts.ModuleResolutionKind.Bundler,
    strict: true,
    skipLibCheck: true,
  });
  const checker = program.getTypeChecker();
  const transport = program.getSourceFile(options.transportSource);
  if (!transport) throw new Error(`Could not load ${options.transportSource}.`);
  const shared = sharedHelpers(transport);
  const collected: Collected = {
    operations: [],
    annotations: [],
    undocumented: [],
    ungrouped: [],
    misgrouped: [],
    unschematized: [],
    unroutable: [],
  };
  const seen = new Set<string>();

  for (const path of options.operationSources) {
    const source = program.getSourceFile(path);
    if (!source) throw new Error(`Could not load ${path}.`);
    const text = readFileSync(path, "utf8");
    const surface = readFileSurface(source);
    for (const declaration of surface.declarations) {
      if (seen.has(declaration.name)) continue;
      // Route first, schemas second: a declaration that never reaches the wire
      // is not an operation, and typing its parameters would file coverage
      // gaps against a function the catalog does not contain. The route is also
      // what identifies each parameter - `/agents/{x}` says `x` is an agent.
      const routing = extractRoute(declaration, callerParameters(declaration), {
        surface,
        shared,
      });
      // Nothing reaches the wire: a pure client-side computation, not an
      // operation a caller could ever dispatch.
      if (routing.reason === "no request call") continue;
      seen.add(declaration.name);
      const docs = parseAssistantDocs(
        leadingJsDoc(text, declaration.node.getStart(source)),
      );
      const { params, unschematized, openIdentifiers } = parametersOf(
        declaration,
        checker,
        source,
        {
          docs: docs.params,
          route: routing.route,
          operation: declaration.name,
        },
      );
      if (routing.reason !== null)
        collected.unroutable.push({
          name: declaration.name,
          reason: routing.reason,
        });
      if (!docs.description) collected.undocumented.push(declaration.name);
      if (!docs.group) collected.ungrouped.push(declaration.name);
      else if (!ASSISTANT_GROUPS.includes(docs.group))
        collected.misgrouped.push(`${declaration.name}: ${docs.group}`);
      const returnType = returnsOf(declaration, checker);
      const returns = returnType
        ? schemaForType(checker, returnType, declaration.node)
        : { $comment: "unschematized: unknown" };
      if (isFallback(returns)) unschematized.push("returns");
      collected.unschematized.push(
        ...unschematized.map((field) => `${declaration.name}.${field}`),
      );
      collected.operations.push({
        name: declaration.name,
        group: docs.group || "system",
        description: docs.description ?? humanizeMethodName(declaration.name),
        confirm: docs.confirm,
        hidden: docs.hidden,
        ...(docs.hiddenReason ? { hiddenReason: docs.hiddenReason } : {}),
        ...(docs.unconfirmed ? { unconfirmed: docs.unconfirmed } : {}),
        params,
        returns,
        route: routing.route,
      });
      collected.annotations.push({
        name: declaration.name,
        location: declarationLocation(declaration, source),
        documented: docs.description !== undefined,
        group: docs.group,
        hidden: docs.hidden,
        hiddenReason: docs.hiddenReason,
        method: routing.route?.method,
        confirm: docs.confirm,
        unconfirmed: docs.unconfirmed,
        unroutableReason: docs.unroutableReason,
        unschematizedReason: docs.unschematizedReason,
        unknownTags: docs.unknownTags,
        routable: routing.route !== null,
        unschematizedFields: unschematized,
        openIdentifiers,
      });
    }
  }

  const byGroupThenName = (
    left: { group?: string; name: string },
    right: { group?: string; name: string },
  ): number =>
    (left.group || "system").localeCompare(right.group || "system") ||
    left.name.localeCompare(right.name);
  collected.operations.sort(byGroupThenName);
  collected.annotations.sort(byGroupThenName);
  collected.unroutable.sort((left, right) =>
    left.name.localeCompare(right.name),
  );
  return {
    catalog: {
      $comment: CATALOG_COMMENT,
      version: ASSISTANT_CATALOG_VERSION,
      sourceHash: hashSources(files),
      operations: collected.operations,
    },
    coverage: {
      undocumented: collected.undocumented,
      ungrouped: collected.ungrouped,
      misgrouped: collected.misgrouped,
      unschematized: collected.unschematized,
      hidden: collected.operations
        .filter((operation) => operation.hidden)
        .map((operation) => operation.name),
      unroutable: collected.unroutable,
    },
    annotations: collected.annotations,
  };
}
